name: labels

# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  label-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hramos/label-actions@v1
        with:
          configuration-path: .github/workflows/labels-config.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
